### ISSUE TITLE
Evolve code into library vs. cli

### ISSUE THREAD

**Issue by humphd** [SeanPrashad/Lust#11]
One thing I notice about the code right now is that it assumes it's being called from the command line, much as you'd invoke `git` or the like.  This is OK for testing things out at first, but what if I want to use this in my GUI application, or in a web service, and just need to call the functions without having a shell running?

It would be good to evolve the code so that you have a set of functions that don't assume anything about UI (e.g., don't `println`) and instead take input and return output (which could also be an error).  You're using the `sha1` crate, which is an example of what I'm talking about; you should check out how they structure their code: https://github.com/mitsuhiko/rust-sha1/blob/master/src/lib.rs

When you write a library, you want to remove all assumptions about how it will be used at the level of user interaction, and instead think in terms of API and dev interaction within a larger piece of code.  You then can write a simple CLI that *uses* your API to do what you've done (i.e., don't throw this other code away, just wrap it around your actual API).

I think you've chosen this approach because it gives you quick feedback as you develop to know if something is working or not: you want an easy way to test your code.  A better way is to write some unit tests for these functions, and then use `cargo test` to run over all your test cases.

Rust does a great job of doing this, and lets you write tests in the same file as you write your code.  Check out how the `sha1` create you're using does testing: https://github.com/mitsuhiko/rust-sha1/blob/master/src/lib.rs#L258.

You basically want to take each of your functions, and start coming up with all the ways people could use and abuse them.  What if you pass in a filename that doesn't exist?  What about passing in an empty file? etc.

**Comment by SeanPrashad** [comment]
Initial switchover from `main.rs` to `lib.rs` with commit 3cdf31440b79eab32a7ae28b79cf61b975328c2d

**Comment by SeanPrashad** [comment]
*TODO*: Begin writing Unit Tests - reference(s): https://doc.rust-lang.org/book/second-edition/ch11-01-writing-tests.html

**Comment by SeanPrashad** [comment]
Completed all unit tests as well as utilized the `[crypto](https://crates.io/crates/rust-crypto)` library for sha1/md5 hashing functionality. Resolved with commit 2b8f3f731188dfb021e5a3cd23bcd479bb7cd4ac
