### ISSUE TITLE
Implement functionality for getFileSize()

### ISSUE THREAD

**Issue by SeanPrashad** [SeanPrashad/Lust#2]

**Comment by jselmani** [comment]
Can I claim this bug, @SeanPrashad?

**Comment by SeanPrashad** [comment]
Sure @jselmani - I've assigned this bug to you

**Comment by jselmani** [comment]
Thanks @SeanPrashad!

**Comment by SeanPrashad** [comment]
Start your search here @jselmani: https://doc.rust-lang.org/nightly/std/fs/struct.Metadata.html#method.len

**Comment by SeanPrashad** [comment]
Also from David H:https://github.com/japaric/steed/blob/7b5394449f1070d0dd2848f25ace3e0a6287dfeb/examples/stat.rs & https://github.com/search?l=Rust&q=Metadata+file+size&type=Code&utf8=%E2%9C%93

**Comment by SeanPrashad** [comment]
Let's modify the version of the code I pushed to not have to parse a Result: https://doc.rust-lang.org/std/result/enum.Result.html

**Comment by jselmani** [comment]
Sounds good to me @SeanPrashad

**Comment by SeanPrashad** [comment]
Resolved with 3cdf31440b79eab32a7ae28b79cf61b975328c2d
