### ISSUE TITLE
Implement loop functionality

### ISSUE THREAD

**Issue by SeanPrashad** [SeanPrashad/Lust#6]
It'd be nice if we could continuously specify a file to retrieve metadata about until the user enters "q" or "Q"!

Looking into how to use loops in Rust would be a great start: https://rustbyexample.com/flow_control/loop.html

**Comment by marcobeltempo** [comment]
Hey @SeanPrashad, I would be interested in taking this on.
Were you thinking to accept a command line argument and then prompt the use for another file?
Or prompt the user after running the app?

**Comment by SeanPrashad** [comment]
Hey @marcobeltempo! We'd love to bring you on board - I was thinking it would accept an initial command line argument, then keep asking for a file path until the user wants to quit ('q' or "Q" is entered). What do you think about this?

**Comment by marcobeltempo** [comment]
@SeanPrashad looking forward to collaborating with you guys!
Yea I think that's a good idea

**Comment by SeanPrashad** [comment]
Furthermore, maybe have a file structure with different files: `dog/lazydog.txt`, `cat/lazycat.txt`, `professor/lazyprofessor.txt` with each file varying in contents and size. Try to make one of them over 1 MB for one of the other open issues!
